reviewers:
  docs:
    - vkab18

  backend:
    - bacdev2

  frontend:
    - forntdev

files:
  docs:
    - "README.md"
    - "docs/**"

  backend:
    - "backend/**"

  frontend:
    - "frontend/**"
