documentation:
  - changed-files:
      - any-glob-to-any-file: README.md
      - any-glob-to-any-file: docs/**

ci:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**

code:
  - changed-files:
      - any-glob-to-any-file: src/**
